---
# Maps inforesid to a url in the style of the "servers" field of swagger/openapi/smartapi.
#
# Provided for purposes of pushing code without breaking any services not yet registered
# on smart-api with the required x-maturity field.  Once all services are registered on smart-api with
# x-maturity, url-config-legacy.yaml should be deleted.

# url-config-legacy.yaml is not a way for the ARS to avoid a successful request to smart-api.info in order
# to be ready to serve requests.
infores:aragorn: https://aragorn.ci.transltr.io/aragorn
infores:arax: https://arax.ci.transltr.io/api/arax/v1.4
infores:biothings-explorer: https://bte.ci.transltr.io/v1
infores:shepherd-aragorn: https://shepherd.renci.org/aragorn
infores:shepherd-arax: https://shepherd.renci.org/arax
infores:shepherd-bte: https://shepherd.renci.org/bte
infores:shepherd-sipr: https://shepherd.renci.org/sipr
infores:improving-agent: https://ia.ci.transltr.io/api/v1.5/
infores:unsecret-agent: https://medikanren-trapi.ci.transltr.io
infores:workflow-runner: https://translator-workflow-runner.ci.transltr.io
infores:cqs: https://cqs.ci.transltr.io
infores:automat-cam-kp: https://automat.ci.transltr.io/cam-kp
infores:connections-hypothesis: https://chp-api.ci.transltr.io
infores:cohd: https://cohd-api.ci.transltr.io/api
infores:genetics-data-provider: https://genetics-kp.ci.transltr.io/genetics_provider/trapi/v1.5
infores:multiomics-clinicaltrials: https://multiomics.ci.transltr.io/ctkp
infores:multiomics-drugapprovals: https://multiomics.ci.transltr.io/dakp
infores:molepro: https://molepro-trapi.ci.transltr.io/molepro/trapi/v1.5
infores:openpredict: https://openpredict.ci.transltr.io
infores:text-mining-provider-targeted: https://biothings.ci.transltr.io/text_mining_targeted_association
